<a href="https://colab.research.google.com/github/deva-kumari/devakumari_cse22237/blob/main/LAB3-O2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load dataset
data = load_iris()
X = data.data
y = data.target

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# List of metrics to evaluate
metrics = ['euclidean', 'manhattan', 'minkowski', 'chebyshev']
results = {}

# Train and evaluate kNN classifier with different metrics
for metric in metrics:
    # Create the kNN classifier with k=3 and the specified metric
    neigh = KNeighborsClassifier(n_neighbors=3, metric=metric)

    # Train the classifier
    neigh.fit(X_train, y_train)

    # Evaluate the classifier using the test set
    y_pred = neigh.predict(X_test)

    # Store the results
    accuracy = neigh.score(X_test, y_test)
    results[metric] = {
        'accuracy': accuracy,
        'classification_report': classification_report(y_test, y_pred),
        'confusion_matrix': confusion_matrix(y_test, y_pred)
    }

# Print the results
for metric, metrics_results in results.items():
    print(f"Distance Metric: {metric}")
    print(f"Accuracy: {metrics_results['accuracy']:.2f}")
    print("Classification Report:")
    print(metrics_results['classification_report'])
    print("Confusion Matrix:")
    print(metrics_results['confusion_matrix'])
    print("="*50)


Distance Metric: euclidean
Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Distance Metric: manhattan
Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]